# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Changes
      labels:
        - Semver-Major
        - breaking-change
    - title: Features
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
